name: libpoisson
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - cupy
  - numba
  - numpy
  - pip
  - pytest
  - scipy

  # CUDA stack
  - cuda-version<=12.9
  - cuda-libraries-dev
  - cuda-compiler
  - cmake >= 3.24
  - make
  - cxx-compiler
  - c-compiler
  - blas-devel
  - libblas
  - liblapacke
  - nanobind
  - stochasticHydroTools::spreadinterp
  - pip:
    - sphinx==8.1.3
    - sphinx-rtd-theme==3.0.2
    - sphinxcontrib-autoprogram==0.1.9
    - sphinxcontrib-napoleon==0.7
    - gitpython
