name: libpoisson
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python > 3.13
  - cupy
  - numba
  - numpy
  - pip
  - pytest
  - scipy
  - cuda-version==12.3
  - cuda-libraries-dev
  - cuda-compiler
  - mkl-devel
  - cmake
  - make
  - cxx-compiler
  - blas-devel
  - libblas
  - liblapacke
  - nanobind
  - pip:
    - sphinx==8.1.3
    - sphinx-rtd-theme==3.0.2
    - sphinxcontrib-autoprogram==0.1.9
    - sphinxcontrib-napoleon==0.7
    - gitpython
    - git+https://github.com/RaulPPelaez/spreadinterp
